### ISSUE TITLE
Library not available - Script ID 

### ISSUE THREAD

**Issue by sebexer** [neojato/coinbase-lib#1]
When looking up the Script ID (1zfKYbXu33sgYgWPE6SKaFdeY-pqTWV5hEPBU4CSFs1dwKJDGfE0F55rF) within Apps Script I get the following error:

Unable to look up library. Check the ID and access permissions and try again.

Is the library still available?

**Comment by neojato** [comment]
Library is still available, make sure you are clicking the "+" icon next to "Libraries"  and then pasting the Script ID into the field.

![Screenshot](https://github.com/neojato/coinbase-lib/assets/6041047/70840327-ddf6-40e4-b5e4-d04f48eafdb3)
